import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className="p-8 flex items-center justify-between">
                    <img src="/printforge-logo.png" alt="logo" className="hidden md:block"/>
                    <img src="/printforge-logo-mobile.png" alt="logo" className="md:hidden"/>
                    <ul>
                        <li className="inline-block px-4 text-xl uppercase">3D Models</li>
                        <li className="inline-block px-4 text-xl uppercase">About</li>
                    </ul>
                </header>
                {children}
            </body>
        </html>
    );
}
