import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Albert_Sans, Montserrat_Alternates} from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import printforgeLogo from "@/assets/images/printforge-logo.png";
import printforgeLogoMobile from "@/assets/images/printforge-logo-mobile.png";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const albertSans = Albert_Sans({
    subsets: ["latin"],
    variable: "--font-albert-sans"
})

const montserratAlternates = Montserrat_Alternates({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-montserrat-alternates"
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${albertSans.variable} ${montserratAlternates.variable}`}>
                <header className="w-11/12 mx-auto py-8 flex items-center justify-between">
                    <Link href="/">
                        <Image
                            src={printforgeLogo}
                            alt="logo"
                            className="hidden md:block"/>
                        <Image
                            src={printforgeLogoMobile}
                            alt="logo"
                            className="md:hidden"
                        />
                    </Link>
                    <ul>
                        <li className="inline-block px-4 text-xl uppercase"><Link href="/3d-models">3D Models</Link></li>
                        <li className="inline-block px-4 text-xl uppercase"><Link href="/about">About</Link></li>
                    </ul>
                </header>
                {children}
            </body>
        </html>
    );
}
